name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "ap-south-1"
  AWS_ACCOUNT_ID: "683213329249"
  ROLE_TO_ASSUME: "GitHub_identity_provider"
  NODE_VERSION: "22"
  S3_BUCKET: "hrms-website-vrpi"
  CLOUDFRONT_DISTRIBUTION_ID: "EH914YPBL3WQK"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-role-session

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Clean node_modules and cache
        run: |
          rm -rf node_modules
          npm cache clean --force
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install missing fonts (typeface-poppins)
        run: npm install --legacy-peer-deps typeface-poppins

      - name: Build React app
        env:
          NODE_PATH: ./src
          CI: false
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
